// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyAspNetApp.Data;

#nullable disable

namespace MyAspNetApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyAspNetApp.Models.FourMData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AfterChangeRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeChangeRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initiatordept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initiatorid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initiatormail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturingApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Partcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Partname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcurementApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SafetyApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedSub")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourcingApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time_Stamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("4m_data", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
